package com.miaoshaproject.dao;

import com.miaoshaproject.dataObject.SequenceDO;

public interface SequenceDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table squence_info
     *
     * @mbg.generated Thu Mar 25 23:27:20 CST 2021
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table squence_info
     *
     * @mbg.generated Thu Mar 25 23:27:20 CST 2021
     */
    int insert(SequenceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table squence_info
     *
     * @mbg.generated Thu Mar 25 23:27:20 CST 2021
     */
    int insertSelective(SequenceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table squence_info
     *
     * @mbg.generated Thu Mar 25 23:27:20 CST 2021
     */
    SequenceDO selectByPrimaryKey(String name);

    SequenceDO getSequenceByName(String name);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table squence_info
     *
     * @mbg.generated Thu Mar 25 23:27:20 CST 2021
     */
    int updateByPrimaryKeySelective(SequenceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table squence_info
     *
     * @mbg.generated Thu Mar 25 23:27:20 CST 2021
     */
    int updateByPrimaryKey(SequenceDO record);
}